# Generated by Django 5.1.6 on 2025-03-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_delete_tbl_product'),
        ('Guest', '0006_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=30)),
                ('delivery_email', models.CharField(max_length=30)),
                ('delivery_contact', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(max_length=30)),
                ('delivery_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('delivery_proof', models.FileField(upload_to='Assets/User/Photo/')),
                ('delivery_password', models.CharField(max_length=30)),
                ('delivery_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
