# Generated by Django 5.1.6 on 2025-03-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_delete_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
