# Generated by Django 5.1.6 on 2025-03-31 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_delivery'),
        ('User', '0020_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='deliveryboy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_delivery'),
        ),
    ]
